### ISSUE TITLE
Pending bumps @ 2020-02-20

### ISSUE THREAD

**Issue by kentfredric** [kentnl-gentoo-rust/rust-dev-overlay#42]
Just canonicalizing my offline text file into a todo list, for visiblity.

- [x] clang-sys 0.28.1 -> 0.29.0 e4eb222
- [x] scopeguard 1.0.0 -> 1.1.0 4bb5996f
- [x] serde_test 1.0.102 -> 1.0.104 0934ef29
- [x] tracing-futures 0.2.1 -> 0.2.2 0e8d8785
- [x] regex-syntax 0.6.12 -> 0.6.14 4de81802
- [x] sha1-asm 0.4.3 -> 0.4.4 3c30d20b
- [x] tokio-signal 0.2.7 -> 0.2.9 6c398fde
- [x] serde_bytes 0.10.4 -> 0.10.5 d7c28954
- [x] tokio-timer 0.2.12 -> 0.2.13 720ad994
- [x] thread-local 0.3.6 -> 1.0.1 b5035316
- [x] rustversion 1.0.1 -> 1.0.2 bcad3c98
- [x] console 0.9.1 -> 0.9.2 33c84407
- [x] futures-util 0.3.1 -> 0.3.4 814a2c65 e26ba0bc #43
- [x] futures-executor 0.3.1 -> 0.3.4 7895aabb #43
- [x] futures 0.3.1 -> 0.3.4 302e1ebf #43
- [x] quickcheck 0.9.0 -> 0.9.2 bfe3837
- [x] rand_jitter 0.1.4 -> 0.2.0 168476ac
- [x] ring 0.16.9 -> 0.16.11 49c8266a
- [x] rustls-native-certs 0.1.0 -> 0.2.1 6e74f35a
- [x] webpki-roots 0.18.0 -> 0.19.0 df89365c
- [x] tokio 0.2.9 -> 0.2.11 9cf91a6d
- [x] regex 1.3.1 -> 1.3.4 7a31c608
- [x] rand_os 0.1.3 -> 0.2.2 fc0ed186
- [x] seahash 3.0.6 -> 4.0.0 c857b17f
- [x] smallvec 1.1.0 -> 1.2.0 f19fa1d4
- [x] rustfix 0.4.6 -> 0.5.0 bf8c94f2
- [x] signal-hook 0.1.12 -> 0.1.13 34adaf55
- [x] static_assertions 0.3.4 -> 1.1.0 caab0085
- [x] lexical-core 0.4.6 -> 0.7.4 6631f6ea
- [x] tokio-reactor-0.1.11 -> 0.1.12 f51c268e
- [x] smallvec 0.6.10 -> 0.6.13 bfab6548 #44
- [x] indexmap 1.3.1 -> 1.3.2 7536e968
- [x] rspec 1.0.0-beta.3 -> 1.0.0-beta.4 1760b918 #45
- [x] serde_cbor 0.9.0 -> 0.11.1 cf8507a9
- [x] quickcheck_macros 0.8.0 -> 0.9.1 58ae336e
- [x] seahash 3.0.6 -> 3.0.7 37d1c71c
- [x] ucd-util 0.1.5 -> 0.1.7 813ec5e8
- [x] tokio-tcp 0.1.3 -> 0.1.4 77e98ad7
- [x] streaming-stats 0.2.2 -> 0.2.3 a39100e8
- [x] webpki 0.21.0 -> 0.21.2 ba0812f8
- [x] tokio-sync 0.1.7 -> 0.1.8 6ee9be22
- [x] tokio-process 0.2.4 -> 0.2.5 6f3305f4
- [x] termcolor 1.0.5 -> 1.1.0 e1dece9a
- [x] walkdir 2.2.9 -> 2.3.1 19e81c4f
- [x] lazy_static 1.1.0 -> 1.1.1 35d4fe51
- [x] same-file 1.0.5 -> 1.0.6 5df3e98e
- [x] strsim 0.8.0 -> 0.10.0 0334863b
- [x] tokio-fs 0.1.6 -> 0.1.7 60377840
- [x] toml 0.5.3 -> 0.5.6 1e41d5ae
- [x] serde_json 1.0.41 -> 1.0.48 cffcde58
- [x] winapi 0.2.8 -> 0.3.8 a52f441d
- [x] synstructure 0.12.1 -> 0.12.3 845ed9ec
- [x] serde-big-array 0.1.5 -> 0.2.0 181c11f4
- [x] tokio-current-thread 0.1.6 -> 0.1.7 47d25ffb
- [x] thiserror 1.0.6 -> 1.0.11 32e8bda6
- [x] cpp_demangle 0.2.13 -> 0.2.14 f70c1f7f
- [x] futures-test 0.3.1 -> 0.3.4 046ded03
- [x] rand 0.7.2 -> 0.7.3 2a92f861
- [x] half 1.4.0 -> 1.4.1 5a7653e5
- [x] ryu 1.0.1 -> 1.0.2 d0163a06
- [x] sval 0.4.7 -> 0.5.1 2ec1de35
- [x] pulldown-cmark 0.4.1 -> 0.7.0 283d0325 #46 
- [x] average 0.10.3 -> 0.10.4 fd2e30ac
- [x] autocfg 0.1.6 -> 0.1.7 ff0e2753
- [x] ci_info 0.3.1 -> 0.9.2 8f4f275e #47
- [x] cookie 0.12.0 -> 0.13.3 d7d0332f
- [x] unicode-width 0.1.6 -> 0.1.7 efdcab94
